### ISSUE TITLE
Add Dark Theme similar to Discord's Developer Page

### ISSUE THREAD

**Issue by Nexus237** [devakira/konomi-bots#4] opened 2018-07-22 15:27 UTC
As the white background is cancerous and causes strain to the eye, it would be better to add an option to make the website dark and make it similar to this Discord Developer page which is sexy af 

https://cdn.discordapp.com/attachments/414826075810693130/470608442655113216/unknown.png

**Comment by devakira** [comment] 2018-07-22 15:29
Duplicate of #3

**Closed** 2018-07-22 15:29 UTC
Labels: duplicate, enhancement
